export const COLORS = {
  HTML: "rgb(74 222 128)",
  CSS: "rgb(180 83 9)",
  Javascript: "rgb(220 38 38)",
  Typescript: "rgb(14 165 233)",
  Tailwind: "rgb(2 132 199)",
  React: "rgb(245 158 11)",
  "Next.js": "rgb(37 99 235)",
};

export const TAGS = [
  "HTML",
  "CSS",
  "Javascript",
  "Typescript",
  "Tailwind",
  "React",
  "Next.js",
  "HTML",
  "CSS",
  "Javascript",
  "Typescript",
  "Tailwind",
  "React",
  "Next.js",
  "HTML",
  "CSS",
  "Javascript",
  "Typescript",
  "Tailwind",
  "React",
  "Next.js",
];
